export const QUERY_KEYS = {
  AUTH_ME: ['auth', 'me'] as const,
  SWIPE_DECK: ['swipe', 'deck'] as const,
  PROPERTIES: ['properties'] as const,
  PROPERTY: (id: string) => ['properties', id] as const,
  MY_MATCHES: ['matches'] as const,
  MATCH: (id: string) => ['matches', id] as const,
  CONVERSATIONS: ['conversations'] as const,
  MESSAGES: (conversationId: string) => ['messages', conversationId] as const,
  FAVORITES: ['favorites'] as const,
  ADMIN_STATS: ['admin', 'stats'] as const,
  ADMIN_USERS: ['admin', 'users'] as const,
  ADMIN_USER: (id: string) => ['admin', 'users', id] as const,
  ADMIN_PROPERTIES: ['admin', 'properties'] as const,
  ADMIN_USER_PROPERTIES: (userId: string) => ['admin', 'users', userId, 'properties'] as const,
} as const;
